# Group vars for sympa servers


sympa:
  db:
    app_user: sympa
    app_password: {{ vault_secrets.db.app_password }}
    readonly_user: sympareadonly
    readonly_password: {{ vault_secrets.db.readonly_password }}
  lists_path: /var/lib/sympa/list_data
  arc_path: /var/lib/sympa/archives
