install:
  - ./scripts/create_new_environment.sh environments/local
  - echo "localhost ansible_host=localhost" > environments/local/inventory
  - echo "" >> environments/local/inventory
  - echo "[sympa]" >> environments/local/inventory
  - echo "localhost" >> environments/local/inventory
  - ansible-playbook site.yml -i environments/local/inventory
  
