---

## Template for Sympa virtual robot creation and setup
## templates are called from the sympa/meta/main.yml file

# TODO : paramètres : fqdn, 
- name : "robot {{ robot.mail.domain }}: create list_data directory" 
  file: path="{{ sympa.lists_path }}/{{ robot.mail.domain }}" state=directory owner=sympa group=sympa

- name : "robot {{ robot.mail.domain }}: create etc directory" 
  file: path="{{ install_prefix }}/{{ sympa.install_dir_name }}/etc/{{ robot.mail.domain }}" state=directory owner=sympa group=sympa

- name: "robot {{ robot.mail.domain }}: install robot.conf" 
  template: src=robot.conf.j2 dest="{{ install_prefix }}/{{ sympa.install_dir_name }}/etc/{{ robot.mail.domain }}/robot.conf" mode=0640 owner=sympa group=sympa
  notify: restart sympa
  
# TODO : créer conf postfix
# TODO : conf réseau/hostname
# TODO : ajout mail aliases pour ce robot
# TODO : cert x.509 pour Apache
# TODO : CSS, logo et favicon







