- name: Download sources from repository
  git:
    repo: "{{ sympa_repository }}"
    dest: "{{ sympa_install_prefix }}/src/{{ source_dir }}"
    force: yes
    version: "{{ sympa_repo_version }}"

- name: Prepare configure
  shell: autoreconf -i
  args:
    chdir: "{{ sympa_install_prefix }}/src/{{ source_dir }}"
    executable: /bin/bash

