---

- name: Add sympa group
  group: name=sympa

- name: Add sympa user
  user: name=sympa group=sympa password=no
  
- name: Create sympa directories
  file: dest=/home/{{ item }} state=directory mode=755 owner=sympa
  with_items: ['sympa', 'sympa/src']

- name: Download Sympa tar.gz
  get_url:
    url: "{{ sympa_download_url }}"
    dest: "/home/sympa/src"
    sha256sum: "{{ sympa_sha256 }}"

- name: Create the Sympa src directory
  file: path=/home/sympa/src/sympa-{{ sympa_version }} state=directory
  
- name: Unpack the tarball
  unarchive: src=/home/sympa/src/sympa-{{ sympa_version }}.tar.gz dest=/home/sympa/src/ copy=no creates=/home/sympa/src/sympa-{{ sympa_version }}/README
  
- name: Install Sympa
  shell: ./configure --with-lockdir=/var/lock --with-initdir=/etc/init.d  && make && make install
  args:
    chdir: "/home/sympa/src/sympa-{{ sympa_version }}"
    executable: /bin/bash

- name: Install Sympa configuration file
  template: src=sympa.conf.j2 dest=/etc/sympa/sympa.conf owner=sympa group=sympa mode=0640
  tags: sympa_conf
  notify: restart sympa
  
- name: Install custom syslog-ng.conf file
  template: src=syslog-ng/sympa.conf.j2 dest=/etc/syslog-ng/conf.d/sympa.conf mode=0644
  tags: syslog
  