---
# Configure postfix and mail aliases

- name: Install Postfix main.cf configuration file
  template: src=postfix/main.cf.j2 dest=/etc/postfix/main.cf
  notify: restart postfix
  
- name: Create required /etc/mail/ directory    
  file: dest=/etc/mail state=directory mode=755 owner=sympa group=sympa

- name: Install Sympa mail aliases
  template: src=postfix/sympa_aliases.j2 dest=/etc/mail/sympa_aliases owner=sympa group=sympa mode=0664 force=no
