---

- name: Add sympa user
  user: name=sympa group=sympa password=no
  
- name: Create sympa directories
  file: dest={{ item }} state=directory mode=755 owner=sympa
  with_items: ["{{ sympa_install_prefix }}", "{{ sympa_install_prefix }}/src"]

- name: Check Sympa tar.gz existence
  stat: path="{{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}.tar.gz"
  register: sympa_archive_file

- name: Download Sympa tar.gz
  get_url:
    url: "{{ sympa_download_url }}"
    dest: "{{ sympa_install_prefix }}/src"
    sha256sum: "{{ sympa_sha256[sympa_version] }}"
  when: not sympa_archive_file.stat.exists

- name: Create the Sympa src directory
  file: path={{ sympa_install_prefix }}/src/sympa-{{ sympa_version }} state=directory
  
- name: Unpack the tarball
  unarchive: src={{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}.tar.gz dest={{ sympa_install_prefix }}/src/ copy=no creates={{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}/README

- name: Apply Sympa patches
  patch:
    src: "{{ item }}"
    basedir: "{{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}"
    strip: 1
  when: sympa_apply_patches
  with_fileglob: "{{ role_path }}/patches/{{ sympa_version }}/*.diff"

- name: "Install Sympa [1/3: configure]"
  shell: ./configure --prefix={{ sympa_install_prefix }} --with-lockdir=/var/lock --without-initdir --with-unitsdir=/lib/systemd/system
  args:
    chdir: "{{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}"
    executable: /bin/bash

- name: "Install Sympa [2/3: make]"
  shell: make
  args:
    chdir: "{{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}"
    executable: /bin/bash

- name: "Install Sympa [3/3: make install]"
  shell: make install
  args:
    chdir: "{{ sympa_install_prefix }}/src/sympa-{{ sympa_version }}"
    executable: /bin/bash

- name: Install Sympa configuration file
  template: src=sympa.conf.j2 dest=/etc/sympa/sympa.conf owner=sympa group=sympa mode=0640
  tags: sympa_conf
  notify: restart sympa
  
- name: Create sympa log file
  file: dest=/var/log/sympa state=touch mode=622 owner=syslog group=adm
  tags: syslog
  
- name: Install custom rsyslog conf file
  template: src=rsyslog/sympa.conf.j2 dest=/etc/rsyslog.d/sympa.conf mode=0644
  tags: syslog
  notify: restart rsyslog

- name: Configure logrotate
  template: src=logrotate/sympa.j2 dest=/etc/logrotate.d/sympa mode=0644
  tags: logrotate
  
