---

sympa_source: http://www.sympa.org/distribution
sympa_version: 6.2.22
sympa_download_url: "{{ sympa_source }}/sympa-{{ sympa_version }}.tar.gz"
sympa_sha256:
    { "6.2.22": "21f5e90f5f911c7f8d24b88b0cf45668545da5b45b7cf30138ba144eace6c8b7"}

sympa_install_prefix: /usr/local/sympa