# handlers for the environment specific tasks of the common role

- name: restart postfix
  service: name=postfix state=restarted

- name: update postfix aliases database
  command: /usr/bin/newaliases

- name: restart sympa
  service: name=sympa state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart apache
  service: name=apache2 state=restarted
