---

- name: Ensure SMTP checker dir
  file:
    dest: "{{ install_prefix }}/check_smtp"
    state: directory
    mode: 0755

- name: Create Sympa SMTP checker group
  group:
    name: monitoring
    state: present
  when: '"sympa" in group_names'

- name: Add Sympa SMTP checker user
  user:
    name: monitoring
    group: monitoring
    password: no
  when: '"sympa" in group_names'

- name: Ensure SMTP checker results dir
  file:
    dest: "{{ install_prefix }}/check_smtp/results/{{ item.web.domain }}"
    state: directory
    mode: 0755
    owner: monitoring
    group: monitoring
  loop: "{{ vhost_specific_variables.values()|map(attribute='common')|list }}"
  when: '"sympa" in group_names'

- name: Install required CPAN Perl modules
  apt: name={{ item }} state=present
  with_items:
  - libfile-slurp-perl
  when: '"sympa" in group_names'

- name: Copy Sympa SMTP checker scripts
  copy:
    src: files/monitoring/check_smtp/sympa/
    dest: "{{ install_prefix }}/check_smtp/"
    mode: 0755
    owner: monitoring
    group: monitoring
  when: '"sympa" in group_names'

- name: Copy php SMTP checker scripts
  copy:
    src: files/monitoring/check_smtp/php/
    dest: "{{ install_prefix }}/check_smtp/"
    mode: 0755
  when: '"dokuwiki" in group_names or "limesurvey" in group_names'

- name: Setup SMTP checker config
  template:
    src: "monitoring/check_smtp/check.conf.j2"
    dest: "{{ install_prefix }}/check_smtp/check.conf"

- name: Setup cronjob for Sympa SMTP checker invalidation script
  lineinfile:
    path: "/etc/crontab"
    line: "* * * * * root perl {{ install_prefix }}/check_smtp/invalidate_fails.pl"
  when: '"sympa" in group_names'

- name: Setup cronjob for Sympa SMTP checker sender script
  lineinfile:
    path: "/etc/crontab"
    line: "*/15 * * * * root perl {{ install_prefix }}/check_smtp/send.pl"
  when: '"sympa" in group_names'

- name: Setup cronjob for php SMTP checker sender script
  lineinfile:
    path: "/etc/crontab"
    line: "*/15 * * * * root php {{ install_prefix }}/check_smtp/send.php"
  when: '"dokuwiki" in group_names or "limesurvey" in group_names'

- name: Master.cf configuration
  blockinfile:
    path: /etc/postfix/master.cf
    marker: "# {mark} ANSIBLE MANAGED monitoring transport"
    block: |
      monitoring unix - n n - - pipe
        flags=R user=monitoring argv={{ install_prefix }}/check_smtp/process.pl ${domain}
  notify: restart postfix

- name: Adding required generic transports
  blockinfile:
    path: /etc/postfix/transport
    create: yes
    state: present
    marker: "# {mark} ANSIBLE MANAGED {{ item }} monitoring transports"
    block: |
      {{ common.check_smtp.address }}@{{ item }}          monitoring:{{ common.check_smtp.address }}@{{ item }}
  with_items: "{{ mail_domains }}"

